<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>backup_buddy</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>False</SignAssembly>
    <ApplicationIcon>backup-buddy.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="backup-buddy.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReverseMarkdown" Version="4.7.1" />
  </ItemGroup>

</Project>
